# For more information: https://laravel.com/docs/sail
version: '3.8'

services:
  app:
    build:
      context: ./docker/8.0
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: laravel-realworld-sail-8.0/app
    ports:
      - '${APP_PORT:-80}:80'
    environment:
      PHP_IDE_CONFIG: 'serverName=${COMPOSE_PROJECT_NAME:?}.test'
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - pgsql
      - redis

  pgsql:
    image: 'postgres:13-alpine'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sailpgsql:/var/lib/postgresql/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]

  redis:
    image: 'redis:6-alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sailredis:/data'
    networks:
      - sail
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  sail:
    name: laravel-realworld-network
    driver: bridge

volumes:
  sailpgsql:
    name: laravel-realworld-database
    driver: local
  sailredis:
    name: laravel-realworld-cache
    driver: local
